module.exports = {
  REQUEST_DASHBOARDS: 'REQUEST_DASHBOARDS',
  RECEIVE_DASHBOARDS: 'RECEIVE_DASHBOARDS',
  DISPLAY_MESSAGE: 'DISPLAY_MESSAGE',
  FILTER_DASHBOARDS: 'FILTER_DASHBOARDS',
  ADD_DASHBOARD: 'ADD_DASHBOARD',
  DELETE_DASHBOARD: 'DELETE_DASHBOARD',
  UPDATE_DASHBOARD: 'UPDATE_DASHBOARD'
}