module.exports = {
  REQUEST_CONTENT: 'REQUEST_CONTENT',
  RECEIVE_CONTENT: 'RECEIVE_CONTENT',
  DISPLAY_MESSAGE: 'DISPLAY_MESSAGE',
  CONTENT_NOT_FOUND: 'CONTENT_NOT_FOUND',
  ADD_CONTENT: 'ADD_CONTENT',
  DELETE_CONTENT: 'DELETE_CONTENT',
  UPDATE_CONTENT: 'UPDATE_CONTENT'
}
