module.exports = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  CLEAR_SESSION: 'CLEAR_SESSION',
  VALIDATE_SESSION: 'VALIDATE_SESSION',
  ACTION_LOGOUT: 'ACTION_LOGOUT'
}